config/routes.rb
RailsAppTemplate::Application.routes.draw do
  root 'photos#new'
  resources :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  respond_to :html, :xml
  def index

  end

  def new

  end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  respond_to :html, :xml

  def index
    @photos = Photo.all
    @photo_in_slider = []
      (0..@photos.count).each do |i|
        @photo_in_slider[i] = @photo[i]+@photo[i+1]+@photo[i+2]+@photo[i+3]
      end
    #binding.pry
  end

  def show
    @photo = Photo.find(params[:id])
    @photos = Photo.all
  end

  def create
    @photo = Photo.new(photo_params)
    #binding.pry
    @photo.save
    respond_with(@photo)
  end

  def new
    @photo = Photo.new
    @photos = Photo.all
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_with(@photo)
  end

  private
# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.
    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/landing/index.html.haml
.row
  %h1 Hello World
  =form_for @photo do |form|
    =form.file_field :image
    =form.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: 'utf-8'}
    %title Starter Template

    = stylesheet_link_tag    'application', media: 'all'
    = stylesheet_link_tag    'photos', media: 'all'
    = javascript_include_tag 'application'
    = javascript_include_tag 'jquery.js', 'jquery.event.move', 'responsive-slider.js'
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse
      .container
        .navbar-header
          %button.navbar-toggle{type: 'button', data: {toggle: 'collapse', target: '.navbar-collapse'} }
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Slider', '#', class: 'navbar-brand'
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? 'danger' : 'success' } alert-dismissable" do
          %button.close{type: 'button', data: {dismiss: 'alert'}, aria: {hidden: 'true'} } &times;
          = msg
      = yield

app/views/photos/index.html.haml
.responsive-slider{"data-autoplay" => "true", "data-spy" => "responsive-slider"}
  .slides{"data-group" => "slides"}
    %ul
      -(1..2).each do |list_count|
        %li
          .slide-body{"data-group" => "slide"}
            -(1..@photos.count).each do |image_count|
              =image_tag @photos[list_count+image_count-3].image, :class=> "image-slider"
  %a.slider-control.left{"data-jump" => "prev", :href => "#"} <
  %a.slider-control.right{"data-jump" => "next", :href => "#"} >

= javascript_include_tag 'jquery.js', 'jquery.event.move', 'responsive-slider.js'

app/views/photos/new.html.haml
=form_for @photo, url: photos_path, :html => { :multipart => true } do |form|
  / -if @photos.count < 5
  =form.file_field :image
  =form.submit
- if (@photos.count) >= 4
  = link_to 'Slider', photos_path, class: 'navbar-brand'

app/views/photos/show.html.haml
=image_tag @photo.image.url
=link_to 'New Photo', new_photo_path, class: 'navbar-brand'

-@photos.each do |photo|
  %table
    %tr
    %td= image_tag photo.image, class: 'small-photo'
    %td= link_to 'Delete photo', photo_path(photo), |
         method: :delete,                          |
         data: { confirm: 'Are you sure?' }        |